language: node_js

node_js:
  - "stable"
  
cache:
  directories:
  - node_modules

script:
    - npm test
    - npm run build
    
#if the build is successful, send the generated reports to codecov
after_success:
   - bash <(curl -s https://codecov.io/bash)
